#!/usr/bin/python

import os, sys

home_old = '/home/pbackup/pypix/home/'
home_new = '/home/'
homes = os.listdir(home_old)

for home in homes:
    if not home == 'momo':
    	command = 'sudo cp -ra '+home_old+home+' '+home_new
    	print command
	os.system(command)
