#!/bin/bash
#
# usage: migrate-shadow shadow-like-file>
#
# remarks: the shadow password file must be a copy of passwd that contains
#          only the entries to be migrated.
#

[ -f $1 ] || exit 1

userlist=$(cat $1)
elsebranch=

echo -e "BEGIN { FS=\":\" }\n{"

for entry in $userlist ; do
        username=$(echo $entry | cut -d ':' -f 1)
        encpassword=$(echo $entry | cut -d ':' -f 2)
        echo "${elsebranch}if ( \$0 ~ /^$username:/ ) \
                printf \"%s:%s:%s:%s:%s:%s:%s:%s:%s\n\",\$1, \
                \"$encpassword\", \$3,\$4,\$5,\$6,\$7,\$8,\$9;"
        elsebranch="else "
done

echo "else print \$0;"
echo -e "}\nEND {}"